#!/usr/bin/env python3
"""One source for bundled legal documents and their public Markdown counterparts."""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[1]
EMAIL = 'sosambus@icloud.com'
DATE = '2026-09-30'
DATA = {
'en': {
'privacy': ('Privacy Policy', [
('Who is responsible', 'Stajanka is an independent parking companion developed by Daniil Bortnik. Contact: sosambus@icloud.com. Stajanka does not operate parking areas, issue fines or act as a bank. There is no account creation or sign-in in the app.'),
('Data on your device', 'The app stores the plates, countries and optional nicknames you enter, your selected vehicle, language, and locally recorded parking attempts and paid periods. Vehicles and parking records are kept in a SQLite database on your device. Existing garage and parking records from earlier app versions are migrated to this database without deleting them. History contains parking recorded or confirmed on this device; it is not a complete statement of an external account. There is no developer-operated cloud database or cloud synchronization. iOS backups may contain local app data according to your device settings.'),
('Parking service requests', 'To calculate a price, open checkout and verify parking, the app sends the selected plate, payment-zone identifier, duration, start time and vehicle tariff to Parkouka.by over HTTPS without signing into a Parkouka account. Adding or selecting a vehicle can also check its current paid time across the supported zones. This can restore current paid coverage for the plate, including parking paid elsewhere, but does not retrieve old transactions or their amounts. The country flag and nickname are local display data; they are not sent as parking-payment parameters. Parkouka and the parking operator retain their own transaction records under their policies.'),
('No account connection', 'Stajanka does not request a Parkouka email or password, register vehicles in an external account, fetch account history or retain a login session. On upgrading from an earlier version, the app removes its saved Parkouka login credentials and session cookies. This does not delete an account or records held by the external service. Payment providers and banks may still require authentication within their own checkout interface.'),
('Location and notifications', 'With your permission, foreground location is used to show your position and nearby parking in Apple Maps. The app does not send your GPS location to Parkouka.by or to a developer server. You can use the map manually and revoke location access in iOS Settings. Local expiry reminders require notification permission; this app does not operate a remote push-notification service.'),
('Payments and provider pages', 'ERIP opens a banking app or its payment website. Card checkout is provided by bePaid and may redirect to your bank for authentication. Card numbers, CVCs, cardholder details and bank credentials are entered in the provider or bank interface. Stajanka’s native code does not read or persist those fields. Provider pages may collect transaction, network and device-security data and use their own cookies and scripts. Network providers necessarily receive connection information such as your IP address. Their retention and processing are governed by their own notices.'),
('Analytics and support', 'The native app contains no advertising SDK, advertising identifier access or developer analytics service. Embedded payment and merchant pages use web analytics, including cookie or browser identifiers and information about page interactions. These data support analytics, operation and security of the external services; they are not used for cross-service advertising tracking. The selected parking zone also conveys an approximate parking location, without transmitting GPS coordinates. The developer does not sell personal data or use it for advertising profiles. If you email support, the developer receives your email address and the information you choose to include, for handling that request and any applicable recordkeeping duties. Do not send card numbers, CVCs, banking passwords or one-time codes.'),
('Deletion and your choices', 'Deleting a vehicle from the garage removes that garage entry; locally recorded parking sessions remain. Garage → About and data → Delete local data removes saved vehicles, local parking history, reminders and payment web data from this device. It does not cancel a payment or delete records held by Parkouka, bePaid or a bank. Contact support for questions about access, correction or deletion of information held by the developer.'),
('Scope and changes', 'The app is intended for people arranging lawful parking, not specifically for children. Service providers may process data in other countries under their own policies. We will update this policy when the app’s processing changes and show the revision date. Mandatory privacy rights under applicable law remain unaffected.')]),
'terms': ('Terms of Use', [
('Independent service', 'Stajanka provides a native interface for finding and paying for parking in Minsk. It is an independent app and is not presented as an official product of Parkouka.by, a parking operator, bePaid or a bank. Parking information and payment calculation are supplied by Parkouka.by; the base map is Apple Maps.'),
('Your parking', 'Before paying, check the vehicle plate, zone number on the physical sign, vehicle category, duration and amount. A map marker is not a guarantee of a free space or permission to park. Follow signs and applicable parking rules. Do not operate the app while driving.'),
('Prices and payments', 'The app is free and does not add its own parking service fee or subscription. Parking is a real-world service paid to the relevant operator through ERIP or bePaid. The final amount comes from the parking service. Bank or currency-conversion charges, if any, are determined by your provider. Opening or closing checkout is not proof that payment succeeded.'),
('Confirmation and reminders', 'The app checks the service’s current paid coverage for the selected plate and zone. A local parking record is not a bank receipt or a complete account statement. Restored current coverage can lack historical transaction amounts. Network failures and provider delays can postpone confirmation. Reminders depend on iOS permissions and device state and are not a guarantee against expiry. If payment is uncertain, check the bank result before paying again and keep your receipt.'),
('Refunds and external records', 'For incorrect charges, refunds or disputes about parking, contact the payment recipient or parking operator through its official channels at https://parkouka.by/home/show/contact. Removing a vehicle or clearing app data does not reverse a payment. Stajanka does not create or connect external accounts and cannot delete records held by payment providers or parking operators.'),
('Availability and rights', 'Availability, tariffs and supported zones depend on external services and may change. We will make reasonable efforts to correct app defects reported to sosambus@icloud.com. These terms do not exclude mandatory consumer rights or liability that applicable law does not allow to be excluded. Apple’s standard Licensed Application End User License Agreement applies to the App Store license unless a different license is expressly supplied.')]),
'support': ('Support', [
('Contact', 'Email sosambus@icloud.com for Stajanka support. Include your app version, iOS version, the affected screen and the approximate time of the issue. Crop or redact screenshots before sending them. Do not send payment-card details, bank passwords or one-time codes.'),
('Payment is not confirmed', 'Check whether your bank completed or declined the payment. Return to the Parking tab and refresh. Do not immediately repeat an uncertain payment. If your bank charged you but parking is missing, retain the receipt and contact the parking operator: https://parkouka.by/home/show/contact.'),
('Vehicles and data', 'Use the Delete button on a garage card to remove that vehicle. Its parking records remain. To remove all locally saved vehicles, parking history, reminders and payment web data, open Garage → About and data → Delete local data. This does not delete the operator’s records or cancel paid parking. History is recorded on this device and is not synchronized with other devices or an external account. Checking a saved plate may restore its current paid time, but cannot import a complete transaction history or unknown payment amounts.'),
('Languages and accessibility', 'Belarusian is the default interface language. Use the globe button in the garage to select Russian or English. The map has labeled zoom buttons and optional foreground location. Location and notification permissions can be changed in iOS Settings.'),
('Service scope', 'Stajanka currently shows parking zones in Minsk. All app features are available without creating or signing into an account; there is no Parkouka account screen. A bank or payment provider may require its own checkout authentication. Street names and external bank pages may use the language supplied by their provider.')])},
'ru': {
'privacy': ('Политика конфиденциальности', [
('Кто отвечает за приложение', 'Стаянка — независимое приложение для парковки, разработчик Daniil Bortnik. Контакт: sosambus@icloud.com. Стаянка не управляет парковками, не выписывает штрафы и не является банком. В приложении нет создания аккаунта или входа в него.'),
('Данные на устройстве', 'Приложение сохраняет введенные номера, страны и необязательные названия автомобилей, выбранное авто, язык, локальные попытки оплаты и оплаченные периоды. Автомобили и парковочные записи хранятся в базе SQLite на вашем устройстве. При обновлении ранее сохраненный гараж и парковочные записи переносятся в эту базу без удаления. История содержит парковки, записанные или подтвержденные на этом устройстве; это не полная выписка внешнего кабинета. У разработчика нет собственной облачной базы или облачной синхронизации. Данные приложения могут попадать в резервные копии iOS согласно настройкам устройства.'),
('Запросы к сервису парковок', 'Для расчета стоимости, открытия оплаты и проверки парковки номер автомобиля, идентификатор зоны, длительность, время начала и тариф автомобиля передаются Parkouka.by по HTTPS без входа в кабинет Parkouka. Добавление или выбор авто также может проверять его текущее оплаченное время по поддерживаемым зонам. Так можно восстановить действующую оплаченную парковку по номеру, в том числе оплаченную другим способом, но не прошлые транзакции и их суммы. Страна и название машины используются для локального отображения и не передаются как параметры оплаты. Parkouka и оператор хранят свои записи о платежах по собственным правилам.'),
('Без подключения аккаунта', 'Стаянка не запрашивает почту или пароль Parkouka, не добавляет автомобили во внешний кабинет, не загружает его историю и не сохраняет сеанс входа. При обновлении с прежней версии приложение удаляет сохраненные им данные входа и cookies сессии Parkouka. Это не удаляет аккаунт и записи у внешнего сервиса. Платежный провайдер или банк по-прежнему может запросить подтверждение личности в собственном интерфейсе оплаты.'),
('Геолокация и уведомления', 'С вашего разрешения геолокация во время использования показывает ваше положение и парковки рядом на Apple Maps. GPS-координаты не передаются приложением в Parkouka.by или на сервер разработчика. Карту можно использовать вручную; доступ отключается в настройках iOS. Локальные напоминания требуют разрешения на уведомления. Собственного сервиса удаленных push-уведомлений у приложения нет.'),
('Оплата и страницы провайдеров', 'ЕРИП открывает банковскую программу или платежную страницу. Оплату картой обеспечивает bePaid; для проверки может открыться страница банка. Номер карты, CVC, имя держателя и банковские данные вводятся в интерфейсе провайдера или банка. Нативный код Стаянки не читает и не сохраняет эти поля. Страницы провайдеров могут собирать данные о транзакции, сети и устройстве для безопасности, использовать cookies и собственные скрипты. Сетевые сервисы получают техническую информацию соединения, включая IP-адрес. Их обработка и сроки хранения регулируются собственными уведомлениями.'),
('Аналитика и поддержка', 'В нативном приложении нет рекламных SDK, доступа к рекламному идентификатору и аналитического сервера разработчика. Встроенные платежные страницы и страницы оператора используют веб-аналитику: идентификаторы cookie или браузера и сведения о взаимодействиях со страницами. Эти данные используются для аналитики, работы и безопасности внешних сервисов, без межсервисного рекламного отслеживания. Выбранная зона также сообщает примерное место парковки, без передачи GPS-координат. Разработчик не продает персональные данные и не строит рекламные профили. При обращении по email разработчик получает вашу почту и сведения, которые вы сами включили, для решения вопроса и обязательного по закону учета. Не присылайте номера карт, CVC, банковские пароли и одноразовые коды.'),
('Удаление и выбор пользователя', 'Удаление авто из гаража убирает запись автомобиля; локальные сеансы парковки остаются. Гараж → О приложении и данные → Удалить локальные данные очищает машины, локальную историю, напоминания и веб-данные оплаты на этом устройстве. Это не отменяет платежи и не удаляет записи Parkouka, bePaid или банка. Вопросы доступа, исправления и удаления сведений у разработчика направляйте в поддержку.'),
('Область действия и изменения', 'Приложение предназначено для законной парковки и не ориентировано специально на детей. Внешние провайдеры могут обрабатывать данные в других странах по своим правилам. При изменении обработки мы обновим эту политику и дату редакции. Обязательные права по применимому законодательству сохраняются.')]),
'terms': ('Условия использования', [
('Независимый сервис', 'Стаянка помогает находить и оплачивать парковку в Минске через нативный интерфейс. Это независимое приложение, не представленное как официальный продукт Parkouka.by, оператора парковок, bePaid или банка. Данные зон и расчет оплаты предоставляет Parkouka.by, базовую карту — Apple Maps.'),
('Ваша парковка', 'Перед оплатой проверьте номер авто, зону на дорожном знаке, категорию транспорта, длительность и сумму. Метка на карте не гарантирует свободное место или разрешение парковаться. Соблюдайте знаки и действующие правила. Не пользуйтесь приложением во время управления автомобилем.'),
('Стоимость и платежи', 'Приложение бесплатно и не добавляет собственную комиссию за парковку или подписку. Оплачивается реальная услуга соответствующего оператора через ЕРИП или bePaid. Итоговую сумму возвращает сервис парковок. Комиссии банка и конвертация валюты, если они есть, определяются вашим провайдером. Открытие или закрытие платежной страницы не подтверждает успешную оплату.'),
('Подтверждение и напоминания', 'Приложение проверяет текущее оплаченное время для выбранных номера и зоны в сервисе парковок. Локальная парковочная запись не является банковским чеком или полной выпиской кабинета. У восстановленной действующей парковки может отсутствовать сумма прошлой транзакции. Ошибки сети и задержки провайдера могут задержать подтверждение. Напоминания зависят от разрешений и состояния iOS и не гарантируют защиту от окончания срока. При сомнении проверьте результат в банке до повторной оплаты и сохраните чек.'),
('Возвраты и внешние записи', 'По ошибочным списаниям, возвратам и спорным вопросам парковки обращайтесь к получателю платежа или оператору по официальным контактам: https://parkouka.by/home/show/contact. Удаление машины и очистка данных приложения не возвращают деньги. Стаянка не создает и не подключает внешние аккаунты и не может удалять записи платежных провайдеров или операторов парковок.'),
('Доступность и права', 'Работа, тарифы и доступные зоны зависят от внешних сервисов и могут меняться. О неисправностях приложения сообщайте на sosambus@icloud.com. Мы будем принимать разумные меры для исправления. Эти условия не исключают обязательные права потребителей или ответственность, которую нельзя исключить по закону. К лицензии App Store применяется стандартное лицензионное соглашение Apple, если явно не предоставлено другое.')]),
'support': ('Поддержка', [
('Связаться с разработчиком', 'Поддержка Стаянки: sosambus@icloud.com. Укажите версию приложения и iOS, проблемный экран и примерное время ошибки. Обрежьте или скройте личные данные на скриншотах. Не отправляйте реквизиты карт, банковские пароли и одноразовые коды.'),
('Оплата не подтверждена', 'Проверьте, завершил ли банк платеж или отклонил его. Вернитесь на вкладку парковки и обновите данные. Не повторяйте сразу неопределенный платеж. Если деньги списаны, а парковки нет, сохраните чек и обратитесь к оператору: https://parkouka.by/home/show/contact.'),
('Автомобили и данные', 'Кнопка удаления на карточке гаража убирает автомобиль, сохраняя его парковочные записи. Полная очистка доступна через Гараж → О приложении и данные → Удалить локальные данные. Она убирает автомобили, локальную историю, напоминания и веб-данные оплаты, но не записи оператора и не оплаченную парковку. История записывается на этом устройстве и не синхронизируется с другими устройствами или внешним кабинетом. Проверка сохраненного номера может восстановить текущее оплаченное время, но не полную историю транзакций и неизвестные суммы платежей.'),
('Языки и доступность', 'Основной язык — белорусский. Через кнопку глобуса в гараже доступны русский и английский. На карте есть подписанные кнопки масштаба и необязательная геолокация. Разрешения на геолокацию и уведомления меняются в настройках iOS.'),
('Где работает приложение', 'Стаянка показывает парковочные зоны Минска. Все функции приложения доступны без регистрации и входа; экрана кабинета Parkouka нет. Банк или платежный провайдер может запросить авторизацию при оплате. Названия улиц и внешние банковские страницы могут оставаться на языке их поставщика.')])},
'be': {
'privacy': ('Палітыка прыватнасці', [
('Хто адказвае за праграму', 'Стаянка — незалежная праграма для паркоўкі, распрацоўшчык Daniil Bortnik. Кантакт: sosambus@icloud.com. Стаянка не кіруе паркоўкамі, не выпісвае штрафы і не з’яўляецца банкам. У праграме няма стварэння акаўнта або ўваходу ў яго.'),
('Даныя на прыладзе', 'Праграма захоўвае ўведзеныя нумары, краіны і неабавязковыя назвы аўтамабіляў, выбранае аўто, мову, лакальныя спробы аплаты і аплачаныя перыяды. Аўтамабілі і парковачныя запісы захоўваюцца ў базе SQLite на вашай прыладзе. Пры абнаўленні раней захаваны гараж і парковачныя запісы пераносяцца ў гэтую базу без выдалення. Гісторыя змяшчае паркоўкі, запісаныя або пацверджаныя на гэтай прыладзе; гэта не поўная выпіска знешняга кабінета. У распрацоўшчыка няма ўласнай воблачнай базы або воблачнай сінхранізацыі. Даныя праграмы могуць трапляць у рэзервовыя копіі iOS паводле налад прылады.'),
('Запыты да сэрвісу парковак', 'Для разліку кошту, адкрыцця аплаты і праверкі паркоўкі нумар аўтамабіля, ідэнтыфікатар зоны, працягласць, час пачатку і тарыф перадаюцца Parkouka.by праз HTTPS без уваходу ў кабінет Parkouka. Даданне або выбар аўто таксама можа правяраць яго бягучы аплачаны час па падтрымліваемых зонах. Так можна аднавіць дзейную аплачаную паркоўку па нумары, у тым ліку аплачаную іншым спосабам, але не мінулыя транзакцыі і іх сумы. Краіна і назва аўто выкарыстоўваюцца лакальна і не перадаюцца як параметры аплаты. Parkouka і аператар захоўваюць уласныя запісы пра плацяжы паводле сваіх правілаў.'),
('Без падключэння акаўнта', 'Стаянка не запытвае пошту або пароль Parkouka, не дадае аўтамабілі ў знешні кабінет, не загружае яго гісторыю і не захоўвае сесію ўваходу. Пры абнаўленні з ранейшай версіі праграма выдаляе захаваныя ёю даныя ўваходу і cookies сесіі Parkouka. Гэта не выдаляе акаўнт і запісы ў знешняга сэрвісу. Плацежны правайдар або банк па-ранейшаму можа запытаць пацвярджэнне асобы ва ўласным інтэрфейсе аплаты.'),
('Геалакацыя і апавяшчэнні', 'З вашага дазволу геалакацыя падчас выкарыстання паказвае ваша месца і паркоўкі побач на Apple Maps. GPS-каардынаты не перадаюцца праграмай у Parkouka.by або на сервер распрацоўшчыка. Картай можна карыстацца ўручную; доступ адключаецца ў наладах iOS. Лакальныя напамінкі патрабуюць дазволу на апавяшчэнні. Уласнага сэрвісу аддаленых push-апавяшчэнняў няма.'),
('Аплата і старонкі правайдараў', 'АРІП адкрывае банкаўскую праграму або плацежную старонку. Аплату карткай забяспечвае bePaid; для праверкі можа адкрыцца старонка банка. Нумар карткі, CVC, імя трымальніка і банкаўскія даныя ўводзяцца ў інтэрфейсе правайдара або банка. Натыўны код Стаянкі не чытае і не захоўвае гэтыя палі. Старонкі правайдараў могуць збіраць звесткі пра транзакцыю, сетку і прыладу для бяспекі, выкарыстоўваць cookies і свае скрыпты. Сеткавыя сэрвісы атрымліваюць тэхнічныя звесткі злучэння, у тым ліку IP-адрас. Іх апрацоўка і тэрміны захоўвання вызначаюцца ўласнымі паведамленнямі.'),
('Аналітыка і падтрымка', 'У натыўнай праграме няма рэкламных SDK, доступу да рэкламнага ідэнтыфікатара і аналітычнага сервера распрацоўшчыка. Убудаваныя плацежныя старонкі і старонкі аператара выкарыстоўваюць вэб-аналітыку: ідэнтыфікатары cookie або браўзера і звесткі пра ўзаемадзеянне са старонкамі. Гэтыя даныя выкарыстоўваюцца для аналітыкі, працы і бяспекі знешніх сэрвісаў, без міжсэрвіснага рэкламнага адсочвання. Выбраная зона таксама паведамляе прыблізнае месца паркоўкі, без перадачы GPS-каардынат. Распрацоўшчык не прадае персанальныя даныя і не стварае рэкламныя профілі. Калі вы пішаце ў падтрымку, распрацоўшчык атрымлівае вашу пошту і звесткі, якія вы ўключылі, для вырашэння пытання і неабходнага паводле закона ўліку. Не дасылайце нумары картак, CVC, банкаўскія паролі і аднаразовыя коды.'),
('Выдаленне і ваш выбар', 'Выдаленне аўто з гаража прыбірае яго запіс; лакальныя сеансы паркоўкі застаюцца. Гараж → Пра праграму і даныя → Выдаліць лакальныя даныя ачышчае аўто, лакальную гісторыю, напамінкі і вэб-даныя аплаты на гэтай прыладзе. Гэта не адмяняе плацяжы і не выдаляе запісы Parkouka, bePaid або банка. Пытанні доступу, выпраўлення і выдалення звестак у распрацоўшчыка накіроўвайце ў падтрымку.'),
('Вобласць дзеяння і змены', 'Праграма прызначаная для законнай паркоўкі і не арыентаваная спецыяльна на дзяцей. Знешнія правайдары могуць апрацоўваць даныя ў іншых краінах паводле сваіх правілаў. Пры змене апрацоўкі мы абновім гэтую палітыку і дату рэдакцыі. Абавязковыя правы паводле дзейнага заканадаўства захоўваюцца.')]),
'terms': ('Умовы выкарыстання', [
('Незалежны сэрвіс', 'Стаянка дапамагае знаходзіць і аплачваць паркоўку ў Мінску праз натыўны інтэрфейс. Гэта незалежная праграма, якая не прадстаўляецца як афіцыйны прадукт Parkouka.by, аператара парковак, bePaid або банка. Звесткі пра зоны і разлік аплаты дае Parkouka.by, базавую карту — Apple Maps.'),
('Ваша паркоўка', 'Перад аплатай праверце нумар аўто, зону на дарожным знаку, катэгорыю транспарту, працягласць і суму. Метка на карце не гарантуе вольнага месца або дазволу паркавацца. Выконвайце знакі і дзейныя правілы. Не карыстайцеся праграмай падчас кіравання аўтамабілем.'),
('Кошт і плацяжы', 'Праграма бясплатная і не дадае ўласнай камісіі за паркоўку або падпіскі. Аплачваецца рэальная паслуга адпаведнага аператара праз АРІП або bePaid. Канчатковую суму вяртае сэрвіс парковак. Камісіі банка і канвертацыя валюты, калі яны ёсць, вызначаюцца вашым правайдарам. Адкрыццё або закрыццё плацежнай старонкі не пацвярджае паспяховую аплату.'),
('Пацвярджэнне і напамінкі', 'Праграма правярае бягучы аплачаны час для выбраных нумара і зоны ў сэрвісе парковак. Лакальны парковачны запіс не з’яўляецца банкаўскім чэкам або поўнай выпіскай кабінета. У адноўленай дзейнай паркоўкі можа адсутнічаць сума мінулай транзакцыі. Памылкі сеткі і затрымкі правайдара могуць затрымаць пацвярджэнне. Напамінкі залежаць ад дазволаў і стану iOS і не гарантуюць абарону ад заканчэння тэрміну. Пры сумненні праверце вынік у банку перад паўторнай аплатай і захавайце чэк.'),
('Вяртанні і знешнія запісы', 'Пры памылковых спісаннях, вяртанні грошай і спрэчных пытаннях звяртайцеся да атрымальніка плацяжу або аператара праз афіцыйныя кантакты: https://parkouka.by/home/show/contact. Выдаленне аўто і ачыстка даных праграмы не вяртаюць грошы. Стаянка не стварае і не падключае знешнія акаўнты і не можа выдаляць запісы плацежных правайдараў або аператараў парковак.'),
('Даступнасць і правы', 'Праца, тарыфы і даступныя зоны залежаць ад знешніх сэрвісаў і могуць мяняцца. Пра няспраўнасці паведамляйце на sosambus@icloud.com. Мы будзем прымаць разумныя меры для выпраўлення. Гэтыя ўмовы не выключаюць абавязковыя правы спажыўцоў або адказнасць, якую нельга выключыць паводле закона. Да ліцэнзіі App Store прымяняецца стандартнае ліцэнзійнае пагадненне Apple, калі яўна не прадастаўлена іншае.')]),
'support': ('Падтрымка', [
('Звязацца з распрацоўшчыкам', 'Падтрымка Стаянкі: sosambus@icloud.com. Укажыце версію праграмы і iOS, праблемны экран і прыблізны час памылкі. Абрэжце або схавайце асабістыя звесткі на здымках экрана. Не дасылайце рэквізіты картак, банкаўскія паролі і аднаразовыя коды.'),
('Аплата не пацверджаная', 'Праверце, ці завяршыў банк плацёж або адхіліў яго. Вярніцеся на ўкладку паркоўкі і абнавіце даныя. Не паўтарайце адразу нявызначаны плацёж. Калі грошы спісаныя, а паркоўкі няма, захавайце чэк і звярніцеся да аператара: https://parkouka.by/home/show/contact.'),
('Аўтамабілі і даныя', 'Кнопка выдалення на картцы гаража прыбірае аўтамабіль, захоўваючы яго парковачныя запісы. Поўная ачыстка даступная праз Гараж → Пра праграму і даныя → Выдаліць лакальныя даныя. Яна прыбірае аўто, лакальную гісторыю, напамінкі і вэб-даныя аплаты, але не запісы аператара і не аплачаную паркоўку. Гісторыя запісваецца на гэтай прыладзе і не сінхранізуецца з іншымі прыладамі або знешнім кабінетам. Праверка захаванага нумара можа аднавіць бягучы аплачаны час, але не поўную гісторыю транзакцый і невядомыя сумы плацяжоў.'),
('Мовы і даступнасць', 'Асноўная мова — беларуская. Праз кнопку глобуса ў гаражы даступныя руская і англійская. На карце ёсць падпісаныя кнопкі маштабу і неабавязковая геалакацыя. Дазволы на геалакацыю і апавяшчэнні мяняюцца ў наладах iOS.'),
('Дзе працуе праграма', 'Стаянка паказвае парковачныя зоны Мінска. Усе функцыі праграмы даступныя без рэгістрацыі і ўваходу; экрана кабінета Parkouka няма. Банк або плацежны правайдар можа запытаць аўтарызацыю пры аплаце. Назвы вуліц і знешнія банкаўскія старонкі могуць заставацца на мове іх пастаўшчыка.')])}
}
for language, documents in DATA.items():
    for kind, (title, sections) in documents.items():
        document = {'title': title, 'updated': DATE, 'sections': [{'title': t, 'body': b} for t, b in sections]}
        (ROOT / 'Stajanka/Resources' / f'{kind}-{language}.json').write_text(json.dumps(document, ensure_ascii=False, indent=2) + '\n')
        output = ROOT / 'release/policies' / f'{kind}-{language}.md'
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(f'# {title}\n\n{DATE}\n\n' + '\n\n'.join(f'## {t}\n\n{b}' for t,b in sections) + '\n')
print('Generated 9 bundled documents and 9 public Markdown documents')
